fix(CrossAppLogin): Don't recycle messages retrieved from Handler.handleMessage
Otherwise, this is thrown:

java.lang.IllegalStateException: This message cannot be recycled because it is still in use.
	at android.os.Message.recycle(Message.java:313)